### ISSUE TITLE
Integrate CHIP as a Submodule

### ISSUE THREAD

**Issue by vringar** [OpenFogStack/matterHub#1]
We should follow the style provided by [CHIP](https://github.com/project-chip/connectedhomeip) and include them in this repo under `third_party/chip/repo` as a git submodule.

Furthermore, our setup script should call out to `./third_party/chip/repo/scripts/activate.sh` to ensure our environment is configured in a compatible way.

Things that are not part of this ticket:
- Setting up our own gn files to call out to CHIP
- Being able to build CHIP from our base directory

**Comment by Jaunty91** [comment]
since there is no setup script yet, is its implementation part of this issue?

**Comment by vringar** [comment]
Yes. But for now it should only forward to the CHIP repo setup script.
