### ISSUE TITLE
Send command to device

### ISSUE THREAD

**Issue by vringar** [OpenFogStack/matterHub#14]
Assuming that the matterHub has been added to the ACL of your target device by the commissioner, send a command that modifies the devices state.

**Comment by Ti-ger** [comment]
Wo wollen wir den Code dafür einbinden? 
Mein Vorschlag wäre die Commands als "Componets" einzubinden.

**Comment by vringar** [comment]
Yeah, we should look into code organization some more. I found [this](https://esp32.com/viewtopic.php?t=12733) when looking for examples on how to include a static library target in the final binary.
I also don't quite understand where the gn calls happens right now.

I've always worked exclusively with targets, as this is the recommondation for [modern CMake](https://cliutils.gitlab.io/modern-cmake/chapters/intro/dodonot.html) however since we are not using CMake directly but ESP-IDF, we might have to compromise on that.
