### ISSUE TITLE
Figure out where to put our own code

### ISSUE THREAD

**Issue by vringar** [OpenFogStack/matterHub#19]
Dumping links and ideas for later

https://docs.espressif.com/projects/esp-idf/en/release-v3.3/api-guides/build-system-cmake.html

I found [this](https://esp32.com/viewtopic.php?t=12733) when looking for examples on how to include a static library target in the final binary.
I also don't quite understand where the gn calls happens right now.

I've always worked exclusively with targets, as this is the recommondation for [modern CMake](https://cliutils.gitlab.io/modern-cmake/chapters/intro/dodonot.html) however since we are not using CMake directly but ESP-IDF, we might have to compromise on that.

**Comment by vringar** [comment]
https://docs.espressif.com/projects/esp-idf/en/release-v3.3/api-guides/build-system-cmake.html#using-esp-idf-in-custom-cmake-projects

**Comment by Ti-ger** [comment]
Here is an example of how to call gn from esp-idf-cmake: 
https://github.com/project-chip/connectedhomeip/blob/master/config/esp32/components/chip/CMakeLists.txt

**Comment by vringar** [comment]
Okay. I'm giving up on the idea of using separate CMake targets, because I'm unable to figure out a way to get access to the matter_gn project the way they to it [https://github.com/project-chip/connectedhomeip/blob/master/config/esp32/components/chip/CMakeLists.txt].
Instead we'll just have one big component and try very hard to not write too much spaghetti.
